#! /bin/sh

alias ls='ls -h --color=auto'
alias grep='grep --color=auto'
[ -f /usr/bin/packer-color ] && alias packer='packer-color'

alias ..='cd ..'
alias huhu='echo -e "\a"'
alias la='ls -A'
alias ll='ls -AlF'
alias mkdir='mkdir -p'

alias v='vim'
alias g='gvim'
alias n='nvim'
alias vim-py3="vim --cmd \"let g:pymode_python='python3'\""
alias emacs='emacs -nw'

alias wpa='wpa_supplicant -BDwext -iwifi -c/root/wpa_supplicant.conf'
alias wpa_c='wpa_supplicant -BDwext -iwifi -c'

man() {
    env LESS_TERMCAP_mb=$(printf "\e[1;31m") \
        LESS_TERMCAP_md=$(printf "\e[1;31m") \
        LESS_TERMCAP_me=$(printf "\e[0m") \
        LESS_TERMCAP_se=$(printf "\e[0m") \
        LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
        LESS_TERMCAP_ue=$(printf "\e[0m") \
        LESS_TERMCAP_us=$(printf "\e[1;32m") \
        man "$@"
}

xinit() {
    /usr/bin/xinit $* -- :1 -nolisten tcp vt$XDG_VTNR
}
