#!/bin/sh
#
# fluxbox startup-script:
#

# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

#exec fluxbox
exec fluxbox -log "~/.fluxbox/log"
