#!/bin/sh

# Example autostart file

swaybg -m fit -i ~/.bg/earthrise-fhd.png >/dev/null 2>&1 &

kanshi >/dev/null 2>&1 &

sfwbar >/dev/null 2>&1 &

mako >/dev/null 2>&1 &

/usr/lib/polkit-kde-authentication-agent-1 >/dev/null 2>&1 &

# swayidle -w \
# 	timeout 300 'swaylock -f -c 000000' \
# 	timeout 600 'wlopm --off \*' \
# 	resume 'wlopm --on \*' \
# 	before-sleep 'swaylock -f -c 000000' >/dev/null 2>&1 &
swayidle -w \
    timeout 900 'wlopm --off \*' \
    resume 'wlopm --on \*' \
    before-sleep 'swaylock -f -c 000000' \
    >/dev/null 2>&1 &

pgrep emacs >/dev/null || emacs --bg-daemon >/dev/null 2>&1
pgrep mpd >/dev/null || mpd >/dev/null 2>&1 &
